// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

function findTheDifference(s: string, t: string): string {
  return String.fromCharCode(
    t.split("").reduce((acc, cur) => (acc += cur.charCodeAt(0)), 0) -
      s.split("").reduce((acc, cur) => (acc += cur.charCodeAt(0)), 0)
  );
}

console.log(findTheDifference("abc", "abco"));
